export { BentoCard, BentoGrid } from './BentoGrid/BentoGrid';
export { default as Header } from './Header/Header';
export { default as Hero } from './Hero/Hero';
export { default as About } from './About/About';
export { default as Education } from './Education/Education';
export { default as Skills } from './Skills/Skills';
export { default as Projects } from './Projects/Projects';
export { default as Contact } from './Contact/Contact';
export { default as Footer } from './Footer/Footer';
export { default as FloatingDots } from './FloatingDots/FloatingDots';
export { default as ShootingStars } from './ShootingStars/ShootingStars';
export { default as GeometricCircles } from './GeometricCircles/GeometricCircles';
export { FollowCursor } from './FollowCursor/FollowCursor';
